SELECT * FROM EMPLEADO;

SELECT E.Nombre, E.Salario/12 as "12 Pagas", E.Salario/14 as "14 Pagas"
FROM EMPLEADO E;

SELECT COUNT(*) FROM EMPLEADO;

SELECT DISTINCT (E.Nombre)
FROM EMPLEADO E; 

SELECT COUNT(DISTINCT(E.Nombre))
FROM EMPLEADO E;

SELECT E.Nombre, E.Salario
FROM EMPLEADO E
WHERE E.Salario BETWEEN 20000 AND 30000;

SELECT * FROM VUELO;

SELECT * FROM VUELO WHERE Numero IN ("ALA0204", "ALA1804");

SELECT * FROM VUELO WHERE Numero LIKE '%ALA%';

SELECT UPPER(Nombre) FROM EMPLEADO E;

SELECT Salario 
FROM EMPLEADO 
ORDER BY Salario DESC
LIMIT 1 OFFSET 3; 

SELECT MAX(Salario)
FROM EMPLEADO;

SELECT AVG(Salario)
FROM EMPLEADO;

SELECT * FROM REGISTRAR_EMPLEADO;

SELECT Numero, COUNT(*) AS "NEmpleados"
FROM REGISTRAR_EMPLEADO
GROUP BY Numero;

SELECT Numero
FROM REGISTRAR_EMPLEADO
GROUP BY Numero
HAVING COUNT(*) > 1;

SELECT * 
FROM REGISTRAR_EMPLEADO
WHERE Empleado = (SELECT NumEmpleado
				  FROM EMPLEADO
			      WHERE NumEmpleado = 1);
                  
SELECT NumEmpleado, Nombre
FROM EMPLEADO
WHERE NumEmpleado IN (SELECT Distinct(Empleado)	
					 FROM REGISTRAR_EMPLEADO);
                     
SELECT Distinct(Empleado), (SELECT Salario FROM EMPLEADO WHERE Empleado = NumEmpleado) AS "Sueldo"
FROM REGISTRAR_EMPLEADO;

SELECT *
FROM PASAJERO
WHERE EXISTS (SELECT Nombre 
			  FROM REGISTRAR_PASAJERO);
                            
SELECT AP.Constructor, AP.Modelo, A.Matricula
FROM APARATO AP, AVION A
WHERE AP.Modelo = A.Modelo;

