CREATE DATABASE alas_al_aire;

USE alas_al_aire;

CREATE TABLE PASAJERO (
   Nombre VARCHAR(32) NOT NULL,
   Direccion VARCHAR(64) NOT NULL,
   Telefono CHAR(9),
  PRIMARY KEY (Nombre, Direccion)
);

CREATE TABLE EMPLEADO (
   NumEmpleado INT NOT NULL AUTO_INCREMENT,
   Nombre VARCHAR(32) NOT NULL,
   Direccion VARCHAR(64) NOT NULL,
   Salario DECIMAL(7,2),
  PRIMARY KEY (NumEmpleado)
);

CREATE TABLE VUELO (
   Numero CHAR(8) NOT NULL,
   Fecha DATE NOT NULL,
   HoraSalida DATETIME NOT NULL,
   HoraLlegada DATETIME,
   Origen CHAR(3) NOT NULL,
   Destino CHAR(3) NOT NULL,
   Avion CHAR(6) NOT NULL,
   PRIMARY KEY (Numero, Fecha)
);



CREATE TABLE REGISTRAR_PASAJERO (
   Nombre VARCHAR(32) NOT NULL,
   Direccion VARCHAR(64) NOT NULL,
   Numero CHAR(8) NOT NULL,
   Fecha DATE NOT NULL,
  PRIMARY KEY (Nombre, Direccion, Numero, Fecha),
  FOREIGN KEY (Nombre, Direccion) REFERENCES PASAJERO(Nombre, Direccion) 
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (Numero, Fecha) REFERENCES VUELO(Numero, Fecha) 
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE REGISTRAR_EMPLEADO (
   Empleado INT NOT NULL,
   Numero CHAR(8) NOT NULL,
   Fecha DATE NOT NULL,
  PRIMARY KEY (Empleado, Numero, Fecha),
  FOREIGN KEY (Empleado) REFERENCES EMPLEADO(NumEmpleado) 
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (Numero, Fecha) REFERENCES VUELO(Numero, Fecha) 
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE AVION (
   Matricula CHAR(6) NOT NULL,
   Modelo VARCHAR(32) NOT NULL,
  PRIMARY KEY (Matricula)
);

CREATE TABLE APARATO (
   Modelo VARCHAR(32) NOT NULL,
   Constructor VARCHAR(32) NOT NULL,
  PRIMARY KEY (Modelo)
);

ALTER TABLE VUELO ADD FOREIGN KEY (Avion) REFERENCES AVION(Matricula)
    ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE AVION ADD FOREIGN KEY (Modelo) REFERENCES APARATO(Modelo)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE EMPLEADO ADD COLUMN Genero ENUM('M','F');
ALTER TABLE PASAJERO ADD COLUMN Genero ENUM('M','F');