CREATE DATABASE legacy;

USE legacy;

CREATE TABLE AIRCRAFT (
  Hexident CHAR(6) NOT NULL,
  Manufacturer VARCHAR(32) NOT NULL,
  Model VARCHAR(32) NOT NULL,
  Year INT NOT NULL, 
  ADSB BOOLEAN NOT NULL,
  PRIMARY KEY (Hexident)
);

INSERT INTO AIRCRAFT VALUES ("AC4532", "Boeing", "747", 2016, true);
INSERT INTO AIRCRAFT VALUES ("467832", "Airbus", "A320", 2012, true);
INSERT INTO AIRCRAFT VALUES ("CA34B1", "Bombardier", "LearJet 40XR", 2015, false);